name: Formatting Check

on:
    push:
        branches: [ master ]
    pull_request:


jobs:
  formatting-check:

    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: run formatter
      run: |
        poetry run yapf --diff --recursive --verbose thunderbolt test
        poetry run isort --diff thunderbolt test
